# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7096d3cf-2452-43c6-9e17-09a083a08bf8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7096d3cf-2452-43c6-9e17-09a083a08bf8".device = "/dev/disk/by-uuid/7096d3cf-2452-43c6-9e17-09a083a08bf8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4C0F-139A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c54a9405-80b3-4177-a43d-1a3c87c07aec"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
